gitdump:
  # The directory where the git repositories will be dumped
  dump_directory: /home/matt/thmlabs/enum/

# This should be expanded to be all reporting eventually.

# Things that should be configurable here:
# Reporting, output formats.
# AI Prompt templates / custom prompts for analysis.
# Choice of AI for ollama and eventually other providers.
# Wordlists for dirbust / subdomain enum. 